# Generated by Django 4.0.4 on 2022-05-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at']},
        ),
    ]
